version: '3.7'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk
    restart: unless-stopped

  logstash:
    build:
      context: ./logstash
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/patterns:/usr/share/logstash/patterns
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
      LOG_LEVEL: debug
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: unless-stopped

  filebeat:
    build:
      context: ./filebeat
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: filebeat
    volumes:
      - ./logs:/var/log/logs
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/config/inputs.d:/usr/share/filebeat/inputs.d
      - ./filebeat/config/modules.d:/usr/share/filebeat/modules.d
    depends_on:
      - logstash
    networks:
      - elk
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
     - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: unless-stopped


  redis:
    image: redis:5.0-alpine
    container_name: redis
    # ports:
      # - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - elk
    restart: unless-stopped

networks:
  elk:
    name: elk
    driver: bridge
