version: '3.2'

services:
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    restart: unless-stopped

  filebeat:
    build:
      context: ./filebeat
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: filebeat
    volumes:
      - ./filebeat/app.log:/var/log/app.log
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/config/inputs.d:/usr/share/filebeat/inputs.d
      - ./filebeat/config/modules.d:/usr/share/filebeat/modules.d
      # - /var/run/docker.sock:/var/run/docker.sock
    # user: root
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: unless-stopped

  logstash:
    build:
      context: ./logstash
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: unless-stopped

  kibana:
    build:
      context: ./kibana
      args:
        ELK_VERSION: ${ELK_VERSION}
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
     - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk
    restart: unless-stopped

networks:
  elk:
    driver: bridge
